export const categories = [
  { id: 1, slug: "phones", name: "Phones", icon: "/icons/earbuds.png" },
  { id: 2, slug: "tablets", name: "Tablets", icon: "/icons/headphone.png" },
  { id: 3, slug: "laptops", name: "Laptops", icon: "/icons/speaker.png" },
  { id: 4, slug: "desktops", name: "Desktops", icon: "/icons/earbuds.png" },
  { id: 5, slug: "monitors", name: "Monitors", icon: "/icons/headphone.png" },
  {
    id: 6,
    slug: "accessories",
    name: "Accessories",
    icon: "/icons/speaker.png",
  },
  { id: 7, slug: "software", name: "Software", icon: "/icons/earbuds.png" },
  { id: 8, slug: "gaming", name: "Gaming", icon: "/icons/headphone.png" },
  { id: 9, slug: "cameras", name: "Cameras", icon: "/icons/speaker.png" },
  { id: 10, slug: "tvs", name: "TVs", icon: "/icons/earbuds.png" },
  {
    id: 11,
    slug: "smart-home",
    name: "Smart Home",
    icon: "/icons/headphone.png",
  },
  { id: 12, slug: "audio", name: "Audio", icon: "/icons/speaker.png" },
  { id: 13, slug: "cc-camera", name: "CC Camera", icon: "/icons/earbuds.png" },
  {
    id: 14,
    slug: "smart-watch",
    name: "Smart Watch",
    icon: "/icons/headphone.png",
  },
  { id: 15, slug: "drone", name: "Drone", icon: "/icons/speaker.png" },
  { id: 16, slug: "gaming-2", name: "Gaming", icon: "/icons/earbuds.png" },
];
